/// <reference types="cypress" />

context('Purchase items Tests', () => {
  beforeEach(() => {
    cy.visit('http://automationpractice.com')
  })

  it.only('Buy first element from bestsellers', () => {
    cy.get('a.product-name')
      .first()
      .click()
      .get('a.button-plus')
      .click()
      .get("a[name='Blue']")
      .first()
      .click()
      .get("button[name='Submit']")
      .click()
      .get("a.btn-default[title='Proceed to checkout']")
      .click()
      .get("a.btn-default.standard-checkout[title='Proceed to checkout']")
      .first()
      .click()
      .get('#email')
      .type('auto-testers-login+@test.com')
      .get('#passwd')
      .type('@123asdasP8*#!klj')
      .get('#SubmitLogin')
      .click()
      // .get('.hidden')
      // .invoke('show')
      // .get('.hidden')
      // .click({ force: true })
      // .get('h1.page-heading')
      // .should('have.text', 'Addresses')
      .get("a.btn-default[title='Proceed to checkout']")
      .first()
      // .scrollTo('bottomRight')
      .click({ force: true })
      // .get('#cgv')
      // .click()
      // .click()
      // .get("a.btn-default[title='Proceed to checkout']")
      // .first()
      // .click({ force: true })
      // .get("a.btn-default[title='Proceed to checkout']")
      // .first()
      // .click({ force: true }).get("a.btn-default[title='Proceed to checkout']")
      // .first()
      // .click({ force: true })
      // .get('a.bankwire')
      // .click()
      .get("a.btn-default[type='submit']")
      .click()
      .get('p.cheque-indent > strong.dark')
      .first()
      .should('contain', 'Your order on My Store is complete.')

    //a.bankwire
    //submit
    //.get("a.btn-default[title='I confirm my order']")
    //.get("a.btn-default[type='submit']")

    //auto-testers-login+@test.com`
    //@123asdasP8*#!klj')
  })
})
